version: '3'

services:
 mongodb:
  image: mongo
  container_name: mongodb
  ports:
   - 27017:27017
  restarts: always
  environment:
   - MONGO_INITDB_ROOT_USERNAME=root
   - MONGO_INITDB_ROOT_PASSWORD=root
  volumes:
   - data:/data

 mongo-express:
   image: mongo-express
   container_name: mongo-express
   ports:
    - 8081:8081
   restarts: always
   depends_on:
    - mongodb
   environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
 data: {}
